# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/PYNQ-Z1_C.xdc

# Block Designs: bd/Lab3/Lab3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3 || ORIG_REF_NAME==Lab3} -quiet] -quiet

# IP: bd/Lab3/ip/Lab3_processing_system7_0_0/Lab3_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3_processing_system7_0_0 || ORIG_REF_NAME==Lab3_processing_system7_0_0} -quiet] -quiet

# IP: bd/Lab3/ip/Lab3_axi_regmap_0_0/Lab3_axi_regmap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3_axi_regmap_0_0 || ORIG_REF_NAME==Lab3_axi_regmap_0_0} -quiet] -quiet

# IP: bd/Lab3/ip/Lab3_mult_Top_0_0/Lab3_mult_Top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3_mult_Top_0_0 || ORIG_REF_NAME==Lab3_mult_Top_0_0} -quiet] -quiet

# IP: bd/Lab3/ip/Lab3_ps7_0_axi_periph_0/Lab3_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3_ps7_0_axi_periph_0 || ORIG_REF_NAME==Lab3_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Lab3/ip/Lab3_rst_ps7_0_100M_0/Lab3_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3_rst_ps7_0_100M_0 || ORIG_REF_NAME==Lab3_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Lab3/ip/Lab3_slicer_A_0_0/Lab3_slicer_A_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3_slicer_A_0_0 || ORIG_REF_NAME==Lab3_slicer_A_0_0} -quiet] -quiet

# IP: bd/Lab3/ip/Lab3_slicer_B_0_0/Lab3_slicer_B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3_slicer_B_0_0 || ORIG_REF_NAME==Lab3_slicer_B_0_0} -quiet] -quiet

# IP: bd/Lab3/ip/Lab3_auto_pc_0/Lab3_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3_auto_pc_0 || ORIG_REF_NAME==Lab3_auto_pc_0} -quiet] -quiet

# XDC: bd/Lab3/Lab3_ooc.xdc
