# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/RAYAN/AppData/Roaming/Xilinx/Vivado/_Lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_AXI_DMA_0/system_AXI_DMA_0.xci
# IP: The module: 'system_AXI_DMA_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/RAYAN/AppData/Roaming/Xilinx/Vivado/_Lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_AXI_DMA_0/system_AXI_DMA_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_AXI_DMA_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/RAYAN/AppData/Roaming/Xilinx/Vivado/_Lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_AXI_DMA_0/system_AXI_DMA_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_AXI_DMA_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/RAYAN/AppData/Roaming/Xilinx/Vivado/_Lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_AXI_DMA_0/system_AXI_DMA_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_AXI_DMA_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/RAYAN/AppData/Roaming/Xilinx/Vivado/_Lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_AXI_DMA_0/system_AXI_DMA_0.xci
# IP: The module: 'system_AXI_DMA_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/RAYAN/AppData/Roaming/Xilinx/Vivado/_Lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_AXI_DMA_0/system_AXI_DMA_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_AXI_DMA_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/RAYAN/AppData/Roaming/Xilinx/Vivado/_Lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_AXI_DMA_0/system_AXI_DMA_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_AXI_DMA_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/RAYAN/AppData/Roaming/Xilinx/Vivado/_Lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_AXI_DMA_0/system_AXI_DMA_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_AXI_DMA_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
