# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/PYNQ-Z1_C.xdc

# Block Designs: bd/Lab_4/Lab_4.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_4 || ORIG_REF_NAME==Lab_4} -quiet] -quiet

# IP: bd/Lab_4/ip/Lab_4_axi_regmap_0_0/Lab_4_axi_regmap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_4_axi_regmap_0_0 || ORIG_REF_NAME==Lab_4_axi_regmap_0_0} -quiet] -quiet

# IP: bd/Lab_4/ip/Lab_4_processing_system7_0_0/Lab_4_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_4_processing_system7_0_0 || ORIG_REF_NAME==Lab_4_processing_system7_0_0} -quiet] -quiet

# IP: bd/Lab_4/ip/Lab_4_top_level_0_0/Lab_4_top_level_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_4_top_level_0_0 || ORIG_REF_NAME==Lab_4_top_level_0_0} -quiet] -quiet

# IP: bd/Lab_4/ip/Lab_4_xbar_0/Lab_4_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_4_xbar_0 || ORIG_REF_NAME==Lab_4_xbar_0} -quiet] -quiet

# IP: bd/Lab_4/ip/Lab_4_ps7_0_axi_periph_0/Lab_4_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_4_ps7_0_axi_periph_0 || ORIG_REF_NAME==Lab_4_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Lab_4/ip/Lab_4_rst_ps7_0_100M_0/Lab_4_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_4_rst_ps7_0_100M_0 || ORIG_REF_NAME==Lab_4_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Lab_4/ip/Lab_4_blk_mem_gen_0_0/Lab_4_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_4_blk_mem_gen_0_0 || ORIG_REF_NAME==Lab_4_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/Lab_4/ip/Lab_4_axi_bram_ctrl_0_0/Lab_4_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_4_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Lab_4_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/Lab_4/ip/Lab_4_xlconstant_0_0/Lab_4_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_4_xlconstant_0_0 || ORIG_REF_NAME==Lab_4_xlconstant_0_0} -quiet] -quiet

# IP: bd/Lab_4/ip/Lab_4_xlconcat_0_0/Lab_4_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_4_xlconcat_0_0 || ORIG_REF_NAME==Lab_4_xlconcat_0_0} -quiet] -quiet

# IP: bd/Lab_4/ip/Lab_4_auto_pc_0/Lab_4_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_4_auto_pc_0 || ORIG_REF_NAME==Lab_4_auto_pc_0} -quiet] -quiet

# IP: bd/Lab_4/ip/Lab_4_s00_mmu_0/Lab_4_s00_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_4_s00_mmu_0 || ORIG_REF_NAME==Lab_4_s00_mmu_0} -quiet] -quiet

# XDC: bd/Lab_4/Lab_4_ooc.xdc
