---
title: "STAT 1261/2260 Homework 3"
author: "Rayan Hassan"
date: "2023-09-19"
output: html_document
---


```{r}
library(tidyverse)
library(mdsr)
library(babynames)
BabynamesDist <- make_babynames_dist()
head(BabynamesDist,2)
```

# Question 1

```{r}

joseph<-BabynamesDist %>%
  filter(name=="Joseph",sex=="M")

plot <- ggplot(data=joseph,aes(x=year)) +  geom_bar(aes(y = count_thousands * alive_prob),
           stat = "identity", 
           fill = "#b2d7e9", colour = "white")

plot <- plot + geom_line(aes(y = count_thousands), linewidth = 2)

plot <- plot + ylab("Number of People (thousands)") + xlab(NULL)

library(Hmisc) 
median_yob <-
  with(joseph, wtd.quantile(year, est_alive_today, probs = 0.5))
median_yob

plot <- plot +   geom_bar(stat = "identity", colour = "white", fill = "#008fd5",
           aes(y = ifelse(year == median_yob, est_alive_today / 1000, 0)))

plot +   ggtitle("Age Distribution of American Boys Named Joseph") +
  geom_text(x = 1935, y = 40, label = "Number of Josephs \n born each year") +
  geom_text(x = 1915, y = 13, label =
    "Number of Josephs \n born each year \n estimated to be alive \n on 1/1/2014",
    colour = "#b2d7e9") +
  geom_text(x = 2003, y = 40,
    label = "The median \n living Joseph \n is 37 years old",
            colour = "darkgray") +
  geom_curve(x = 1995, xend = 1974, y = 40, yend = 24,
    arrow = arrow(length = unit(0.3,"cm")), curvature = 0.5) + ylim(0, 42)




```

# Question 2

```{r}
Lillian <- filter(BabynamesDist, name == "Lillian" & sex == "F")
plot <- plot %+% Lillian

median_yob <-
  with(Lillian, wtd.quantile(year, est_alive_today, probs = 0.5))
median_yob

plot +   ggtitle("Age Distribution of American Girls Named Lillian") +
  geom_text(x = 1950, y = 9, label = "Number of Lillians \n born each year") +
  geom_text(x = 1910, y = 1, label =
    "Number of Lillians \n born each year \n estimated to be alive \n on 1/1/2014",
    colour = "#b2d7e9") +
  geom_text(x = 1980, y = 5,
    label = "The median \n living Lillian \n is 46 years old",
            colour = "darkgray") +
  geom_curve(x = 1970, xend = 1966, y = 3.5, yend = 1.5,
    arrow = arrow(length = unit(0.3,"cm")), curvature = 0.4) + ylim(0, 10)


```

# Question 3

```{r}
library(MASS)
head(Boston)
dim(Boston)
names(Boston)
```

# Question 4

```{r}
p <- ggplot(data=Boston,aes(x=medv,y=after_stat(density)))
p <- p + geom_histogram(fill="purple",col="white", bins=15) +
  geom_density(linewidth=1) + ggtitle("Histogram of Median House Values")+ xlab("Median House Value (in $1000)")
p

```

# Question 5

```{r}
p <- ggplot(data=Boston,aes(x=rm,y=after_stat(density)))
p <- p + geom_histogram(fill="purple",col="white", bins=15) +
  geom_density(linewidth=1) + ggtitle("Histogram of Average Number of Rooms per Dwelling")+ xlab("Average Number of Rooms per Dwelling")
p
```

# Question 6

```{r}
p = ggplot(data=Boston)+geom_point(mapping=aes(x=medv, y = rm)) + geom_smooth(mapping=aes(x=medv, y = rm))
p
```

# Question 7

```{r}
rm_cat = as.factor(round(Boston$rm))
Boston2 <- data.frame(Boston$medv, rm_cat)
head(Boston2)

ggplot(data=Boston2,aes(rm_cat,Boston$medv))+geom_boxplot()


```

```{r}
rm_cat=Boston$rm
Boston2 <- data.frame(Boston$medv, rm_cat)
head(Boston2)

ggplot(data=Boston2,aes(rm_cat,Boston$medv))+geom_boxplot()
```


So we need to make the conversion otherwise it won't be a side-by-side box plot (rm is continuous variable)
