# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/RAYAN/Lab_2/Lab_2.srcs/sources_1/bd/Lab_2/ip/Lab_2_ila_0_0/Lab_2_ila_0_0.xci
# IP: The module: 'Lab_2_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/RAYAN/Lab_2/Lab_2.srcs/sources_1/bd/Lab_2/ip/Lab_2_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_2_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/RAYAN/Lab_2/Lab_2.srcs/sources_1/bd/Lab_2/ip/Lab_2_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_2_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/RAYAN/Lab_2/Lab_2.srcs/sources_1/bd/Lab_2/ip/Lab_2_ila_0_0/Lab_2_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_2_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/RAYAN/Lab_2/Lab_2.srcs/sources_1/bd/Lab_2/ip/Lab_2_ila_0_0/Lab_2_ila_0_0.xci
# IP: The module: 'Lab_2_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/RAYAN/Lab_2/Lab_2.srcs/sources_1/bd/Lab_2/ip/Lab_2_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_2_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/RAYAN/Lab_2/Lab_2.srcs/sources_1/bd/Lab_2/ip/Lab_2_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_2_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/RAYAN/Lab_2/Lab_2.srcs/sources_1/bd/Lab_2/ip/Lab_2_ila_0_0/Lab_2_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_2_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
