#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 19 13:21:21 2019

@author: ahmadbeydoun
"""

s=input("Enter numbers separated by spaces:")
t=int(input("Enter target number: "))
L=[int(x) for x in s.split()]
is_found=False
for i in range(len(L)):
    for j in range(i,len(L)):
        sum= L[i]+L[j]
        if sum==t:
            is_found=True
            print((L[i],L[j]))
if not is_found:
    print ("The input sequence does not contains any pair of integers whose sum is",t)