CREATE TABLE `149839922`.`wp_anciens`(
    `Promo` INT(4) NOT NULL,
    `Nom` VARCHAR(50) NOT NULL,
    `Prénom` VARCHAR(50) NOT NULL,
    `Email 1` VARCHAR(50) NOT NULL,
    `Email 2` VARCHAR(50) NOT NULL,
    `School ID` INT(8) NOT NULL AUTO_INCREMENT,
    `Année Entrée` INT(4) NOT NULL,
    `Année Sortie` INT(4) NOT NULL,
    `Classe Entrée` VARCHAR(5) NOT NULL,
    `Classe Sortie` VARCHAR(5) NOT NULL,
    `Nombres d'Années` INT(2) NOT NULL,
    `Nom du Pere` VARCHAR(50) NOT NULL,
    `Sexe` ENUM('Homme', 'Femme', 'Autre') NOT NULL,
    `Date de Naissance` DATE NOT NULL,
    `Décédé?` ENUM('Oui', 'Non') NOT NULL,
    `Pays de Résidence` VARCHAR(50) NOT NULL,
    `Ville de Résidence` VARCHAR(50) NOT NULL,
    `Adresse Détaillée` VARCHAR(300) NOT NULL,
    `Téléphone 1` VARCHAR(20) NOT NULL,
    `Portable` VARCHAR(20) NOT NULL,
    `AACLW` ENUM('Oui', 'Non') NOT NULL,
    `Parent d'élève` ENUM('Oui', 'Non') NOT NULL,
    `Information à communiquer` VARCHAR(300) NOT NULL,
    `Université 1` VARCHAR(100) NOT NULL,
    `Pays 1` VARCHAR(100) NOT NULL,
    `Major 1` VARCHAR(100) NOT NULL,
    `Diplome 1` VARCHAR(100) NOT NULL,
    `Université 2` VARCHAR(100) NOT NULL,
    `Pays 2` VARCHAR(100) NOT NULL,
    `Major 2` VARCHAR(100) NOT NULL,
    `Diplome 2` VARCHAR(100) NOT NULL,
    `Université 3` VARCHAR(100) NOT NULL,
    `Pays 3` VARCHAR(100) NOT NULL,
    `Major 3` VARCHAR(100) NOT NULL,
    `Diplome 3` VARCHAR(100) NOT NULL,
    `Secteur (Domaine Professionnel)` VARCHAR(100) NOT NULL,
    `Spécifier` VARCHAR(100) NOT NULL,
    `Nom de l'Entreprise` VARCHAR(100) NOT NULL,
    `Poste occupé` VARCHAR(100) NOT NULL,
    `Prix Obtenu` VARCHAR(100) NOT NULL,
    `Unsubscribe` ENUM('Oui', 'Non') NOT NULL,
    `Number of Times Unsubscribed` INT(2) NOT NULL,
    PRIMARY KEY(`School ID`)
) ENGINE = InnoDB;